# Generated by Django 5.2.1 on 2025-06-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название поля')),
                ('type', models.CharField(choices=[('int', 'Целое число'), ('float', 'Дробное число'), ('date', 'Дата')], verbose_name='Тип поля')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор группы')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Название группы (Опционально)')),
                ('main_username', models.CharField(verbose_name='Юзернейм ответственного')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('type', models.CharField(blank=True, choices=[('video', 'Видео'), ('photo', 'Фото')], null=True, verbose_name='Тип вложения')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Вложение')),
                ('file_id', models.BigIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('name', models.CharField(primary_key=True, serialize=False, verbose_name='Название')),
                ('fields', models.ManyToManyField(to='panel.field', verbose_name='Поля')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
