# Generated by Django 5.2.1 on 2025-06-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_field_group_publication_template_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='file_id',
            field=models.CharField(editable=False, null=True),
        ),
    ]
