# Generated by Django 5.2.1 on 2025-06-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_group_day_report_group_evening_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tried',
            field=models.BooleanField(default=False),
        ),
    ]
